version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.
    networks:
      - mongo-network

  mongosh:
    image: mongo:latest
    container_name: mongosh_container
    command: mongosh
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
    links:
      - mongodb

volumes:
  mongodb_data:

networks:
  mongo-network: